/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MecanicoRouteImport } from './routes/mecanico'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MecanicoIndexRouteImport } from './routes/mecanico.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MecanicoNovaOsRouteImport } from './routes/mecanico.nova-os'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as MecanicoOsOsIdFechamentoRouteImport } from './routes/mecanico.os.$osId.fechamento'
import { Route as MecanicoOsOsIdExecucaoRouteImport } from './routes/mecanico.os.$osId.execucao'

const MecanicoRoute = MecanicoRouteImport.update({
  id: '/mecanico',
  path: '/mecanico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MecanicoIndexRoute = MecanicoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MecanicoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MecanicoNovaOsRoute = MecanicoNovaOsRouteImport.update({
  id: '/nova-os',
  path: '/nova-os',
  getParentRoute: () => MecanicoRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const MecanicoOsOsIdFechamentoRoute =
  MecanicoOsOsIdFechamentoRouteImport.update({
    id: '/os/$osId/fechamento',
    path: '/os/$osId/fechamento',
    getParentRoute: () => MecanicoRoute,
  } as any)
const MecanicoOsOsIdExecucaoRoute = MecanicoOsOsIdExecucaoRouteImport.update({
  id: '/os/$osId/execucao',
  path: '/os/$osId/execucao',
  getParentRoute: () => MecanicoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/mecanico': typeof MecanicoRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/mecanico/nova-os': typeof MecanicoNovaOsRoute
  '/admin/': typeof AdminIndexRoute
  '/mecanico/': typeof MecanicoIndexRoute
  '/mecanico/os/$osId/execucao': typeof MecanicoOsOsIdExecucaoRoute
  '/mecanico/os/$osId/fechamento': typeof MecanicoOsOsIdFechamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/mecanico/nova-os': typeof MecanicoNovaOsRoute
  '/admin': typeof AdminIndexRoute
  '/mecanico': typeof MecanicoIndexRoute
  '/mecanico/os/$osId/execucao': typeof MecanicoOsOsIdExecucaoRoute
  '/mecanico/os/$osId/fechamento': typeof MecanicoOsOsIdFechamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/mecanico': typeof MecanicoRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/mecanico/nova-os': typeof MecanicoNovaOsRoute
  '/admin/': typeof AdminIndexRoute
  '/mecanico/': typeof MecanicoIndexRoute
  '/mecanico/os/$osId/execucao': typeof MecanicoOsOsIdExecucaoRoute
  '/mecanico/os/$osId/fechamento': typeof MecanicoOsOsIdFechamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/mecanico'
    | '/admin/clientes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/mecanico/nova-os'
    | '/admin/'
    | '/mecanico/'
    | '/mecanico/os/$osId/execucao'
    | '/mecanico/os/$osId/fechamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/clientes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/mecanico/nova-os'
    | '/admin'
    | '/mecanico'
    | '/mecanico/os/$osId/execucao'
    | '/mecanico/os/$osId/fechamento'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin'
    | '/mecanico'
    | '/admin/clientes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/mecanico/nova-os'
    | '/admin/'
    | '/mecanico/'
    | '/mecanico/os/$osId/execucao'
    | '/mecanico/os/$osId/fechamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminRoute: typeof AdminRouteWithChildren
  MecanicoRoute: typeof MecanicoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mecanico': {
      id: '/mecanico'
      path: '/mecanico'
      fullPath: '/mecanico'
      preLoaderRoute: typeof MecanicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mecanico/': {
      id: '/mecanico/'
      path: '/'
      fullPath: '/mecanico/'
      preLoaderRoute: typeof MecanicoIndexRouteImport
      parentRoute: typeof MecanicoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mecanico/nova-os': {
      id: '/mecanico/nova-os'
      path: '/nova-os'
      fullPath: '/mecanico/nova-os'
      preLoaderRoute: typeof MecanicoNovaOsRouteImport
      parentRoute: typeof MecanicoRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mecanico/os/$osId/fechamento': {
      id: '/mecanico/os/$osId/fechamento'
      path: '/os/$osId/fechamento'
      fullPath: '/mecanico/os/$osId/fechamento'
      preLoaderRoute: typeof MecanicoOsOsIdFechamentoRouteImport
      parentRoute: typeof MecanicoRoute
    }
    '/mecanico/os/$osId/execucao': {
      id: '/mecanico/os/$osId/execucao'
      path: '/os/$osId/execucao'
      fullPath: '/mecanico/os/$osId/execucao'
      preLoaderRoute: typeof MecanicoOsOsIdExecucaoRouteImport
      parentRoute: typeof MecanicoRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MecanicoRouteChildren {
  MecanicoNovaOsRoute: typeof MecanicoNovaOsRoute
  MecanicoIndexRoute: typeof MecanicoIndexRoute
  MecanicoOsOsIdExecucaoRoute: typeof MecanicoOsOsIdExecucaoRoute
  MecanicoOsOsIdFechamentoRoute: typeof MecanicoOsOsIdFechamentoRoute
}

const MecanicoRouteChildren: MecanicoRouteChildren = {
  MecanicoNovaOsRoute: MecanicoNovaOsRoute,
  MecanicoIndexRoute: MecanicoIndexRoute,
  MecanicoOsOsIdExecucaoRoute: MecanicoOsOsIdExecucaoRoute,
  MecanicoOsOsIdFechamentoRoute: MecanicoOsOsIdFechamentoRoute,
}

const MecanicoRouteWithChildren = MecanicoRoute._addFileChildren(
  MecanicoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminRoute: AdminRouteWithChildren,
  MecanicoRoute: MecanicoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
